%{!?lyrune_version:%global lyrune_version 1.3.0}
%global debug_package %{nil}

Name:           lyrune
Version:        %{lyrune_version}
Release:        1.pixelbar%{?dist}
Summary:        Native QQ Music player with PixelBar Bluetooth lyrics
License:        LicenseRef-Unknown
URL:            https://github.com/amtoaer/lyrune
Source0:        %{name}-%{version}.tar.gz
ExclusiveArch:  x86_64 aarch64

# ELF dependencies (including the minimum glibc version) are generated by RPM.
# GPUI loads the following libraries dynamically, so list them explicitly.
Requires:       libwayland-client.so.0()(64bit)
Requires:       libwayland-cursor.so.0()(64bit)
Requires:       libvulkan.so.1()(64bit)
Requires:       hicolor-icon-theme
Recommends:     bluez

%description
Lyrune is a native QQ Music desktop player for Linux, built with Rust and GPUI.
This build includes synchronized Bluetooth lyrics for Halo PixelBar speakers,
lyric timing adjustment, display testing, and KDE desktop integration.

This package contains a locally compiled release binary. The complete source
and reproducible packaging steps are available in the accompanying checkout.

%prep
%setup -q

%build
# The build-rpm.sh helper compiles the locked Cargo workspace before packaging.

%install
install -Dm755 lyrune %{buildroot}%{_bindir}/lyrune
install -Dm644 lyrune.desktop %{buildroot}%{_datadir}/applications/lyrune.desktop
install -Dm644 lyrune.svg %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/lyrune.svg
for size in 16 22 24 32 48 64 128 256 512; do
    install -Dm644 icons/${size}.png \
        %{buildroot}%{_datadir}/icons/hicolor/${size}x${size}/apps/lyrune.png
done

%files
%{_bindir}/lyrune
%{_datadir}/applications/lyrune.desktop
%{_datadir}/icons/hicolor/scalable/apps/lyrune.svg
%{_datadir}/icons/hicolor/*x*/apps/lyrune.png
%doc README.md THIRD_PARTY_NOTICES.md
%license license-unknown.txt
